server:
  port: 8081

spring:
  profiles:
    include: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # 출력되는 쿼리를 MySql로 변경
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc


# TODO: Notion에 기재 할 것.
# Test OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope: profile, email

